### ISSUE TITLE
Easy way to transfer multiple pictures in a single ssh session

### ISSUE THREAD

**Issue by rcbarnes** [cachapa/RemoteGallery#12]
Rather than a complicated session management system (which re-invents the wheel) or having to wait for extra session initiation overhead equal to the number of pictures transferred, there is an easy alternative:  use the ImageMagick tools to stitch the pictures together into one (using montage), transfer it in a single session, then slice it up on the phone (since you're already using the library to resize the image, combining them in the same command incurs little additional overhead).

A more simple alternative is to concatenate the images into a (technically invalid) byte stream and transfer that to the phone, slicing it based on the known original size of each file.

**Comment by cachapa** [comment]
It's a nice "out of the box" idea, but there are a few problems with it.

First of all, I don't think that session management would be that complicated. For what we need it could be quite simple, even. It's just that all the testing will take a long time, and that's why it hasn't been done yet.

Also, mobile connections tend to be flaky. Transferring a large file has a big chance of failing meaning that the entire thing will have to be downloaded again.
This also breaks the functionality of the images being shown as they are downloaded.

I'm also not sure, but stiching that many images together might have prohibitive memory costs, both in the server, as well as (more importantly), on the device.
